function import_eeg_data_eeglab_bs(file, subName, eventNames)

% Process: Import MEG/EEG: Existing epochs
sFiles = bst_process('CallProcess', 'process_import_data_epoch', [], [], ...
    'subjectname',   subName, ...
    'condition',     '', ...
    'datafile',      {file, 'EEG-EEGLAB'}, ...
    'iepochs',       [], ...
    'eventtypes',    eventNames, ...
    'createcond',    0, ...
    'channelalign',  1, ...
    'usectfcomp',    1, ...
    'usessp',        1, ...
    'freq',          [], ...
    'baseline',      [], ...
    'blsensortypes', 'EEG');
end