function extract_ersd_files(sFiles, cond, sub, namingAtlasName, contraNamingAtlasName)

%% ========================= VARARGIN MANAGAER =============================
if nargin < 5
    contraNamingAtlasName = 'Contralareral_naming_fmri';
end
if nargin < 4
    namingAtlasName = 'naming_fmri';
end
if nargin < 3
    [sub, ~] = bst_get('Subject');
    fprintf("Nessun soggetto selezionato. Procedo a lavorare sul soggetto %s", sub.Name);
else
    if ~isstruct(sub)
        [sub, ~] = bst_get('Subject', sub);
    end
end

if nargin < 2
    error("Nessuna condizione selezionata")
end

if nargin < 1
    error("Nessun file EEG selezionato")
end


%%
% Process: Compute sources [2018]
sourceFile = bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
    'output',  1, ...  % Kernel only: shared
    'inverse', struct(...
         'Comment',        'dSPM-unscaled: EEG', ...
         'InverseMethod',  'minnorm', ...
         'InverseMeasure', 'dspm2018', ...
         'SourceOrient',   {{'fixed'}}, ...
         'Loose',          0.2, ...
         'UseDepth',       1, ...
         'WeightExp',      0.5, ...
         'WeightLimit',    10, ...
         'NoiseMethod',    'diag', ...
         'NoiseReg',       0.1, ...
         'SnrMethod',      'fixed', ...
         'SnrRms',         1e-06, ...
         'SnrFixed',       3, ...
         'ComputeKernel',  1, ...
         'DataTypes',      {{'EEG'}}));
% Process: Set name: naming_source_model
sourceFile = bst_process('CallProcess', 'process_set_comment', sourceFile, [], ...
    'tag',           sprintf('%s_source_model',cond), ...
    'isindex',       1);
%% Scout files
% Extract the surface selected in the user
surfStruct = in_bst_data(sub.Surface(sub.iCortex).FileName);
% availableAtlases = cellfun(@char, {surfStruct.Atlas.Name}, 'UniformOutput', false);
expAtlasIdx = find(strcmp({surfStruct.Atlas.Name}, namingAtlasName));
contraAtlasIdx = find(strcmp({surfStruct.Atlas.Name}, contraNamingAtlasName));

% Parte non controlaterale:
atlasName = surfStruct.Atlas(expAtlasIdx).Name;
atlasScoutsName = {surfStruct.Atlas(expAtlasIdx).Scouts.Label};
% Process: Scout time series: [21 scouts]
scoutFiles = bst_process('CallProcess', 'process_extract_scout', sourceFile, [], ...
    'timewindow',     [], ...
    'scouts',         {atlasName, atlasScoutsName}, ...
    'flatten',        1, ...
    'scoutfunc',      'mean', ...  % Mean
    'pcaedit',        struct(...
         'Method',         'pca', ...
         'Baseline',       [-0.1, 0], ...
         'DataTimeWindow', [0, 1], ...
         'RemoveDcOffset', 'file'), ...
    'isflip',         1, ...
    'isnorm',         0, ...
    'concatenate',    0, ...
    'save',           1, ...
    'addrowcomment',  1, ...
    'addfilecomment', []);

% Process: Set name: naming_sources
scoutFiles = bst_process('CallProcess', 'process_set_comment', scoutFiles, [], ...
    'tag',           'naming_sources', ...
    'isindex',       1);

% Parte controlaterale
atlasName = surfStruct.Atlas(contraAtlasIdx).Name;
atlasScoutsName = {surfStruct.Atlas(contraAtlasIdx).Scouts.Label};

% Process: Scout time series: [21 scouts]
scoutContrFiles = bst_process('CallProcess', 'process_extract_scout', {sourceFile.FileName}', [], ...
    'timewindow',     [], ...
    'scouts',         {atlasName, atlasScoutsName}, ...
    'flatten',        1, ...
    'scoutfunc',      'mean', ...  % Mean
    'pcaedit',        struct(...
         'Method',         'pca', ...
         'Baseline',       [-0.1, 0], ...
         'DataTimeWindow', [0, 1], ...
         'RemoveDcOffset', 'file'), ...
    'isflip',         1, ...
    'isnorm',         0, ...
    'concatenate',    0, ...
    'save',           1, ...
    'addrowcomment',  1, ...
    'addfilecomment', []);

% Process: Set name: naming_sources
scoutContrFiles = bst_process('CallProcess', 'process_set_comment', scoutContrFiles, [], ...
    'tag',           'naming_sources_contralateral', ...
    'isindex',       1);

%%

% Parte non controlaterale
% Process: Time-frequency (Morlet wavelets)
tfFiles = bst_process('CallProcess', 'process_timefreq', scoutFiles, [], ...
    'edit',          struct(...
         'Comment',         'Avg,Power,1-30Hz', ...
         'TimeBands',       [], ...
         'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], ...
         'MorletFc',        1, ...
         'MorletFwhmTc',    3, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'all', ...
         'RemoveEvoked',    0, ...
         'SaveKernel',      0), ...
    'normalize2020', 1, ...
    'normalize',     'none');  % None: Save non-standardized time-frequency maps

% Process: Set name: naming_tf
tfFiles = bst_process('CallProcess', 'process_set_comment', tfFiles, [], ...
    'tag',           'naming_tf', ...
    'isindex',       1);

% Parte controlaterale
% Process: Time-frequency (Morlet wavelets)
tfContrFiles = bst_process('CallProcess', 'process_timefreq', scoutContrFiles, [], ...
    'edit',          struct(...
         'Comment',         'Avg,Power,1-30Hz', ...
         'TimeBands',       [], ...
         'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], ...
         'MorletFc',        1, ...
         'MorletFwhmTc',    3, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'all', ...
         'RemoveEvoked',    0, ...
         'SaveKernel',      0), ...
    'normalize2020', 1, ...
    'normalize',     'none');  % None: Save non-standardized time-frequency maps

% Process: Set name: naming_tf
tfContrFiles = bst_process('CallProcess', 'process_set_comment', tfContrFiles, [], ...
    'tag',           'naming_tf', ...
    'isindex',       1);

%%

% Parte non controlaterale
% Process: Event-related perturbation (ERS/ERD): [-301ms,-4ms]
ersdFiles = bst_process('CallProcess', 'process_baseline_norm', tfFiles, [], ...
    'baseline',  [-0.30078125, -0.00390625], ...
    'method',    'ersd', ...  % Event-related perturbation (ERS/ERD):    x_std = (x - &mu;) / &mu; * 100
    'overwrite', 1);

% Process: Set name: naming_ersd
ersdFiles = bst_process('CallProcess', 'process_set_comment', ersdFiles, [], ...
    'tag',           'naming_ersd', ...
    'isindex',       1);

% Parte controlaterale
% Process: Event-related perturbation (ERS/ERD): [-301ms,-4ms]
ersdContrFiles = bst_process('CallProcess', 'process_baseline_norm', tfContrFiles, [], ...
    'baseline',  [-0.30078125, -0.00390625], ...
    'method',    'ersd', ...  % Event-related perturbation (ERS/ERD):    x_std = (x - &mu;) / &mu; * 100
    'overwrite', 1);

% Process: Set name: naming_ersd
ersdContrFiles = bst_process('CallProcess', 'process_set_comment', ersdContrFiles, [], ...
    'tag',           'naming_ersd_contralateral', ...
    'isindex',       1);

%%

% Parte non controlaterale
% Process: Time-frequency (Morlet wavelets)
phaseFiles = bst_process('CallProcess', 'process_timefreq', scoutFiles, [], ...
    'edit',          struct(...
         'Comment',         'Complex,1-30Hz', ...
         'TimeBands',       [], ...
         'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], ...
         'MorletFc',        1, ...
         'MorletFwhmTc',    3, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'none', ...
         'Output',          'all', ...
         'RemoveEvoked',    0, ...
         'SaveKernel',      0), ...
    'normalize2020', 1, ...
    'normalize',     'none');  % None: Save non-standardized time-frequency maps

% Process: Set name: naming_tf_for_phases
phaseFiles = bst_process('CallProcess', 'process_set_comment', phaseFiles, [], ...
    'tag',           'naming_phases', ...
    'isindex',       1);

% Parte controlaterale
% Process: Time-frequency (Morlet wavelets)
phaseContrFiles = bst_process('CallProcess', 'process_timefreq', scoutContrFiles, [], ...
    'edit',          struct(...
         'Comment',         'Complex,1-30Hz', ...
         'TimeBands',       [], ...
         'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], ...
         'MorletFc',        1, ...
         'MorletFwhmTc',    3, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'none', ...
         'Output',          'all', ...
         'RemoveEvoked',    0, ...
         'SaveKernel',      0), ...
    'normalize2020', 1, ...
    'normalize',     'none');  % None: Save non-standardized time-frequency maps

% Process: Set name: naming_tf_for_phases
phaseContrFiles = bst_process('CallProcess', 'process_set_comment', phaseContrFiles, [], ...
    'tag',           'naming_phases_contralateral', ...
    'isindex',       1);

end