function PPA_extract_scouts(subName,mainDir, varargin)
    %% Varagin manager
    for i = 1:2:length(varargin)
        switch varargin{i}
            case 'abilitate'
                abiltiate = varargin{i+1};
            case 'atlasName'
                atlasName = varargin{i+1};
            case 'scoutsName'
                scoutsName = varargin{i+1};
            case 'cond'
                cond = varargin{i+1};
        end
    end
    
    if ~abiltiate
        fprintf("<strong>Function PPA_fmri_import skipped</strong>\n")
        return
    end

    %% Main

    % Check if sources are already computed

    scoutFiles = bst_process('CallProcess', 'process_select_files_matrix', [], [], ...
            'subjectname',   subName, ...
            'condition',     cond, ...
            'tag',           scoutsName, ...
            'includebad',    0, ...
            'includeintra',  0, ...
            'includecommon', 0, ...
            'outprocesstab', 'no');

    if isempty(scoutFiles)
        % Take EEG files
        eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           cond, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');
        % Find kernel
        dataDir = bst_get('ProtocolInfo').STUDIES;
        kernelFile = dir(fullfile(dataDir, subName, cond, '*KERNEL*'));
        if isempty(kernelFile)
            error("Kernel file non trovato")
        end
        kernelFile = fullfile(kernelFile.folder, kernelFile.name);
        % Take atlas from surface
        [subStruct, ~] = bst_get('Subject', subName);
        surfStruct = in_bst_data(subStruct.Surface(strcmp({subStruct.Surface.Comment},'central_15002V')).FileName);
        atlas = surfStruct.Atlas(strcmp({surfStruct.Atlas.Name}, atlasName));
        atlasScoutsName = {atlas.Scouts.Label};
        sFiles = create_link_files_brainstorm(eegFiles, kernelFile);
        scoutFiles = bst_process('CallProcess', 'process_extract_scout', sFiles, [], ...
            'timewindow',     [], ...
            'scouts',         {atlasName, atlasScoutsName}, ...
            'flatten',        1, ...
            'scoutfunc',      'mean', ...  % Mean
            'pcaedit',        struct(...
                 'Method',         'pca', ...
                 'Baseline',       [-0.1, 0], ...
                 'DataTimeWindow', [0, 1], ...
                 'RemoveDcOffset', 'file'), ...
            'isflip',         1, ...
            'isnorm',         0, ...
            'concatenate',    0, ...
            'save',           1, ...
            'addrowcomment',  1, ...
            'addfilecomment', []);
    
        % Process: Set name: naming_sources
        scoutFiles = bst_process('CallProcess', 'process_set_comment', scoutFiles, [], ...
            'tag',           scoutsName, ...
            'isindex',       1);
    end
end