function PPA_compute_test(subName, mainDir, varargin)
%% Varargin manager

% Default values
filename1 = '';
fileName2 = '';
compName = '';
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'abilitate', abilitate = varargin{i+1};
        case 'fileName1', fileName1 = varargin{i+1};
        case 'fileName2', fileName2 = varargin{i+1};
        case 'compName', compName = varargin{i+1};
        case 'resultType', resultType = varargin{i+1};
    end
end

if ~abilitate
    sprintf("Function PPA_SN_features skipped")
    return
else
    sprintf("Starting function PPA_compute_test")
end

% Mandatory
assert(~isempty(fileName1), 'fileName1 is mandatory for PPA_compute_test');
assert(~isempty(fileName2), 'fileName2 is mandatory for PPA_compute_test');
assert(~isempty(compName), 'compName is mandatory for PPA_compute_test');
assert(~isempty(resultType), 'resultType is mandatory for PPA_compute_test');

%% Compute test if not already computed
compFile = find_presults_bst(subName, compName, 1, resultType);

if isempty(compFile)
% Get files
files1 = bst_process('CallProcess', sprintf('process_select_files_%s',resultType), [], [], ...
                    'subjectname',   subName, ...
                    'condition',     '', ...
                    'tag',           fileName1, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'Process2A');  % No
files1(~cellfun(@(c) strncmp(c, [fileName1 ' '], length(fileName1)+1), {files1.Comment})) = [];
files2 = bst_process('CallProcess', sprintf('process_select_files_%s',resultType), [], [], ...
                    'subjectname',   subName, ...
                    'condition',     '', ...
                    'tag',           fileName2, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'Process2B');  % No
files2(~cellfun(@(c) strncmp(c, [fileName2 ' '], length(fileName2)+1), {files2.Comment})) = [];

% Paired
if numel(files2) == numel(files1)
    compFile = bst_process('CallProcess', 'process_test_permutation2p', files1, files2, ...
                    'timewindow',     [], ...
                    'freqrange',      [1, 45], ...
                    'rows',           '', ...
                    'isabs',          0, ...
                    'avgtime',        0, ...
                    'avgrow',         0, ...
                    'avgfreq',        0, ...
                    'matchrows',      0, ...
                    'iszerobad',      1, ...
                    'Comment',        '', ...
                    'test_type',      'wilcoxon_paired', ...  % Wilcoxon signed-rank test W = sum(sign(A-B) * tiedrank(abs(A-B)))
                    'randomizations', 1000, ...
                    'tail',           'two');  % Two-tailed

else
    % Not paired
    compFile = bst_process('CallProcess', 'process_test_permutation2', files1, files2, ...
                    'timewindow',     [], ...
                    'freqrange',      [1, 45], ...
                    'rows',           '', ...
                    'isabs',          0, ...
                    'avgtime',        0, ...
                    'avgrow',         0, ...
                    'avgfreq',        0, ...
                    'matchrows',      1, ...
                    'iszerobad',      1, ...
                    'Comment',        '', ...
                    'test_type',      'ttest_unequal', ...  % Student's t-test   (unequal variance) t = (mean(A)-mean(B)) / sqrt(var(A)/nA + var(B)/nB)
                    'randomizations', 1000, ...
                    'tail',           'two');  % Two-tailed
    if isempty(compFile)
        disp("Errore nella computazione del file di comparison!")
        keyboard
    end
end
        % Process: Set name
    compFile = bst_process('CallProcess', 'process_set_comment', compFile, [], ...
                    'tag',           compName, ...
                    'isindex',       1);

end
end