function PPA_compute_ERSD_channels(subName, mainDir, varargin)
% PPA_COMPUTE_ERSD_CHANNELS  Computes (or retrieves, if already cached)
%   the channel-level Event-Related Spectral Dynamics (ERSD) for a given
%   subject/condition using Morlet wavelet time-frequency decomposition
%   followed by baseline z-score normalization.
%
%   Parameters (varargin, name-value pairs):
%     cond      - (required) Brainstorm condition folder to process
%     ersdName  - (required) tag used to search for/label the output
%                 ERSD file, so repeated pipeline runs can detect and
%                 skip already-computed results
%     abilitate - bool, if false the function is skipped entirely

% Default values
cond = [];
ersdName = [];
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'ersdName', ersdName = varargin{i+1};
        case 'abilitate', abilitate = varargin{i+1};
        case 'cond', cond = varargin{i+1};
    end
end

if ~abilitate
    sprintf("Function PPA_compute_ERSD_channels skipped")
    return
end

% Required parameters
assert(~isempty(cond), 'Parameter cond is required by extract_band_relative_powers');
assert(~isempty(ersdName), 'Parameter ersdName is required by extract_band_relative_powers');

%% Look for an existing ERSD file
% Search first, so we don't recompute the (expensive) time-frequency
% decomposition if it was already produced by a previous run.
ersdFile = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           ersdName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
if isempty(ersdFile)
    fprintf("PSD file not found for subject %s, computing it now\n", subName);
    eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           cond, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
    eegFiles(~startsWith({eegFiles.Comment}, cond)) = []; % Discard any spurious/unrelated files
    % Process: Time-frequency (Morlet wavelets)
    % Fixed 1-60 Hz linear frequency grid, non-standardized output
    % (normalization is applied separately below, per-baseline).
    ersdFile = bst_process('CallProcess', 'process_timefreq', eegFiles, [], ...
        'edit',          struct(...
             'Comment',         'Power,1-60Hz', ...
             'TimeBands',       [], ...
             'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], ...
             'MorletFc',        1, ...
             'MorletFwhmTc',    3, ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'power', ...
             'Output',          'all', ...
             'RemoveEvoked',    0, ...
             'SaveKernel',      0), ...
        'normalize2020', 1, ...
        'normalize',     'none');  % None: save non-standardized time-frequency maps

    % Process: Z-score transformation over the [-301ms, -4ms] baseline
    % window, so post-stimulus power is expressed relative to the
    % pre-stimulus baseline (standard ERSD normalization).
    ersdFile = bst_process('CallProcess', 'process_baseline_norm', ersdFile, [], ...
        'baseline',  [-0.30078125, -0.00390625], ...
        'method',    'zscore', ...  % Z-score transformation: x_std = (x - mu) / sigma
        'overwrite', 1);
    ersdFile = bst_process('CallProcess', 'process_set_comment', ersdFile, [], ...
            'tag',           ersdName, ...
            'isindex',       1);
end
end
