function PPA_compute_head_model(subName, cond, headModelStruct)

    % NOTE: Electrode positions should already be detected before running
    % head model computation

    [subStruct, iSubject] = bst_get('Subject', subName);
    dataDir = bst_get('ProtocolInfo').STUDIES;
    subFolder = fullfile(dataDir, subName);
    %% Noise covariance check
    cm = dir(fullfile(subFolder, cond, 'noisecov_full.mat'));
    if isempty(cm)
        fprintf("<strong>Noise covariance non trovata, procedo a computarla...</strong>\n")
        eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           cond, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
        iData = [eegFiles.iItem];
        iStudies_data = [eegFiles.iStudy];
        iTargetStudies = unique(iStudies_data);
        bst_noisecov(iTargetStudies, iStudies_data, iData, [], 0);
        cm = dir(fullfile(subFolder, cond, 'noisecov_full.mat'));
    end
    cm = in_bst_data(fullfile(cm.folder,cm.name));
    

    %% BEM check
    % BEM surfaces check
    if (sum(contains({subStruct.Surface.FileName}, 'outerskull') == 1) && ...
        sum(contains({subStruct.Surface.FileName}, 'innerskull') == 1) && ...
        sum(contains({subStruct.Surface.FileName}, 'head_bem') == 1))
        % Check if they are selected on the GUI
        % Innerskull
        panel_protocols('SelectNode', [], subStruct.Surface(contains({subStruct.Surface.FileName}, 'innerskull')).FileName);
        iSurface = find(contains({subStruct.Surface.FileName}, 'innerskull'));
        db_surface_default(iSubject, 'InnerSkull', iSurface);
        panel_protocols('RepaintTree');
        % Outerskull
        panel_protocols('SelectNode', [], subStruct.Surface(contains({subStruct.Surface.FileName}, 'outerskull')).FileName);
        iSurface = find(contains({subStruct.Surface.FileName}, 'outerskull'));
        db_surface_default(iSubject, 'OuterSkull', iSurface);
        panel_protocols('RepaintTree');
        % Head
        panel_protocols('SelectNode', [], subStruct.Surface(contains({subStruct.Surface.FileName}, 'head_bem')).FileName);
        iSurface = find(contains({subStruct.Surface.FileName}, 'head_bem'));
        db_surface_default(iSubject, 'Scalp', iSurface);
        panel_protocols('RepaintTree');
        panel_protocols('UpdateNode',          'Subject', iSubject)
    else
        error('Una o più BEM surfaces non trovate')
    end

    %% Get EEG files
    eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           cond, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
    
    %% Compute head model
    headModelFile = bst_process('CallProcess', 'process_headmodel', eegFiles, [], ...
        'Comment',     '', ...
        'sourcespace', 1, ...  % Cortex surface
        'meg',         4, ...  % OpenMEEG BEM
        'eeg',         3, ...  % OpenMEEG BEM
        'ecog',        2, ...  % OpenMEEG BEM
        'seeg',        2, ...  % OpenMEEG BEM
        'nirs',        1, ...  % 
        'openmeeg',    struct(...
             'BemSelect',    [1, 1, 1], ...
             'BemCond',      headModelStruct.BemCond, ...
             'BemNames',     {{'Scalp', 'Skull', 'Brain'}}, ...
             'BemFiles',     {{}}, ...
             'isAdjoint',    1, ...
             'isAdaptative', 1, ...
             'isSplit',      0, ...
             'SplitLength',  4000), ...
        'nirstorm',    struct(...
             'FluenceFolder',    'https://neuroimage.usc.edu/resources/nst_data/fluence/', ...
             'smoothing_method', 'geodesic_dist', ...
             'smoothing_fwhm',   10), ...
        'channelfile', '');
end