function PPA_tf_phase(subName, mainDir, varargin)

%% ====================== VARARGIN MANAGER ================================
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'abilitate', abilitate = varargin{i+1};
        case 'cond', cond = varargin{i+1};
        case 'tfName', tfName = varargin{i+1};
        case 'searchName', searchName = varargin{i+1};
    end
end

if ~abilitate
    fprintf("Function PPA_tf_phase skipped\n")
    return
end
assert(~isempty(cond), 'cond parameter is mandatory');
assert(~isempty(tfName), 'tfName parameter is mandatory');
assert(~isempty(searchName), 'searchName parameter is mandatory');

%% ============================== MAIN ====================================
% Find if file already exists
phaseFile = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
    'subjectname',   subName, ...
    'condition',     cond, ...
    'tag',           tfName, ...
    'includebad',    0, ...
    'includeintra',  0, ...
    'includecommon', 0, ...
    'outprocesstab', 'no'); 

if ~isempty(phaseFile)
    phaseFile(~cellfun(@(c) strncmp(c, [tfName ' '], length(tfName)+1), {phaseFile.Comment})) = [];
end

if ~isempty(phaseFile)
    return
end

%% ======================== COMPUTE PHASES ===============================
scoutFiles = bst_process('CallProcess', 'process_select_files_matrix', [], [], ...
    'subjectname',   subName, ...
    'condition',     cond, ...
    'tag',           searchName, ...
    'includebad',    0, ...
    'includeintra',  0, ...
    'includecommon', 0, ...
    'outprocesstab', 'no');

scoutFiles(~cellfun(@(c) strncmp(c, searchName, length(searchName)), {scoutFiles.Comment})) = [];

if isempty(scoutFiles)
    error("No scout file found on which to calculate the phases")
end
phaseFiles = bst_process('CallProcess', 'process_timefreq', scoutFiles, [], ...
    'edit',          struct(...
         'Comment',         'Complex,1-60Hz', ...
         'TimeBands',       [], ...
         'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], ...
         'MorletFc',        1, ...
         'MorletFwhmTc',    3, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'none', ...
         'Output',          'all', ...
         'RemoveEvoked',    0, ...
         'SaveKernel',      0), ...
    'normalize2020', 1, ...
    'normalize',     'none');  % None: Save non-standardized time-frequency maps

% Process: Set name: for_ITPC
phaseFiles = bst_process('CallProcess', 'process_set_comment', phaseFiles, [], ...
    'tag',           tfName, ...
    'isindex',       1);
end