function PPA_remove_medial_int_scouts(surfFilename, atlasName)
surfStruct = in_bst_data(surfFilename);
atlas = surfStruct.Atlas(strcmp({surfStruct.Atlas.Name}, atlasName));
if isempty(atlas)
    error("Atlas %s not found!", atlasName)
end

% schafer_100_17net ROI list to remove
schaefAtlas = surfStruct.Atlas(strcmp({surfStruct.Atlas.Name}, 'Schaefer_100_17net'));
if isempty(atlas)
    disp("Atlas Schaefer not found!")
    disp("Manually select scouts to remove, then press f5 to continue")
    keyboard
    return
end
schefList = {'Background+FreeSurfer_Defined_Medial_Wall L',...
    'Background+FreeSurfer_Defined_Medial_Wall L', ...
    'DefaultC_PHC_1 L', 'DefaultC_PHC_1 R',...
    'VisPeri_ExStrInf_1 L','VisPeri_ExStrInf_1 R',...
    'VisCent_ExStr_1 L','VisCent_ExStr_1 R',...
    'VisCent_ExStr_2 L','VisCent_ExStr_2 R',...
    'LimbicA_TempPole_1 L','LimbicA_TempPole_1 R',...
    'DefaultA_pCunPCC_1 L','DefaultA_pCunPCC_1 R',...
    'LimbicB_OFC_1 L','LimbicB_OFC_1 R',...
    'VisPeri_ExStrInf_1 L','VisPeri_ExStrInf_1 R',...
    'DefaultC_Rsp_1 L','DefaultC_Rsp_1 R',...
    'DefaultA_PFCm_1 L','DefaultA_PFCm_1 R',...
    'ContC_Cingp_1 L', 'ContC_Cingp_1 R',...
    'ContC_pCun_1 L','ContC_pCun_1 R',...
    'SalVentAttnB_PFCmp_1 L', 'SalVentAttnB_PFCmp_1 R',...
    'VisCent_ExStr_3 L', 'VisCent_ExStr_3 R',...
    'VisCent_ExStr_2 L', 'VisCent_ExStr_2 R',...
    'VisCent_Striate_1 L','VisCent_Striate_1 R',...
    'DorsAttnA_TempOcc_1 L','DorsAttnA_TempOcc_1 R',...
    'VisPeri_ExStrSup_1 L', 'VisPeri_ExStrSup_1 R',...
    'DorsAttnA_TempOcc_1 R', 'DorsAttnA_TempOcc_1 L',...
    'ContB_Temp_1 R', 'ContB_Temp_1 L',...
    'DefaultB_Temp_1 L','DefaultB_Temp_1 R',...
    'LimbicA_TempPole_1 L','LimbicA_TempPole_1 R'
    };

schefVerts = [];
for sc = 1:numel(schaefAtlas.Scouts)
    if ismember(schaefAtlas.Scouts(sc).Label, schefList)
        schefVerts = [schefVerts; schaefAtlas.Scouts(sc).Vertices'];
    end
end
% Prevent duplicates
schefVerts = unique(schefVerts);

removeIdx = [];
for s = 1:numel(atlas.Scouts)
    scoutVerts = atlas.Scouts(s).Vertices;
    isntAvailable = (length(intersect(scoutVerts, schefVerts)) / length(scoutVerts)) > 0.3;
    if isntAvailable
        removeIdx = [removeIdx; s];
    end
end

if ~isempty(removeIdx)
    atlas.Scouts(removeIdx) = [];
    surfStruct.Atlas(strcmp({surfStruct.Atlas.Name}, atlasName)) = atlas;
    bst_save(file_fullpath(surfFilename), surfStruct, 'v7')
else
    disp("No medial scout to remove")
end