function PPA_compute_ERSD_test(subName, mainDir, varargin)
% PPA_COMPUTE_ERSD_TEST  Runs a within-subject statistical comparison
%   (permutation t-test) between two previously computed ERSD conditions,
%   automatically choosing a paired or unpaired test depending on whether
%   the two conditions have matched trial counts.
%
%   Parameters (varargin, name-value pairs):
%     cond1, cond2         - (required) the two Brainstorm condition
%                             folders to compare
%     ersdName1, ersdName2 - (required) tags identifying the ERSD files
%                             to compare for cond1/cond2 respectively
%     finalName            - (required) tag used to label/find the
%                             resulting comparison file, so the test is
%                             not rerun if already computed
%     abilitate             - bool, if false the function is skipped

% Default values
cond1 = [];
cond2 = [];
ersdName1 = [];
ersdName2 = [];
finalName = [];
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'ersdName1', ersdName1 = varargin{i+1};
        case 'ersdName2', ersdName2 = varargin{i+1};
        case 'cond1', cond1 = varargin{i+1};
        case 'cond2', cond2 = varargin{i+1};
        case 'finalName', finalName = varargin{i+1};
        case 'abilitate', abilitate = varargin{i+1};
    end
end

if ~abilitate
    sprintf("Function PPA_compute_ERSD_test skipped")
    return
end

% Required parameters
assert(~isempty(cond1), 'Parameter cond1 is required by extract_band_relative_powers');
assert(~isempty(cond2), 'Parameter cond2 is required by extract_band_relative_powers');
assert(~isempty(ersdName1), 'Parameter ersdName1 is required by extract_band_relative_powers');
assert(~isempty(ersdName2), 'Parameter ersdName2 is required by extract_band_relative_powers');
assert(~isempty(finalName), 'Parameter finalName is required by extract_band_relative_powers');

%% Compute the within-subject statistical test, if not already done
% Check whether the comparison result already exists, to avoid rerunning
% the (randomization-based) permutation test unnecessarily.
compFile = find_presults_bst(subName, finalName, 1, 'timefreq');
if isempty(compFile)
    ersdFile1 = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     cond1, ...
                    'tag',           ersdName1, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
    ersdFile1(~startsWith({ersdFile1.Comment}, ersdName1)) = [];

    ersdFile2 = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     cond2, ...
                    'tag',           ersdName2, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
    ersdFile2(~startsWith({ersdFile2.Comment}, ersdName2)) = [];

    if isempty(ersdFile1) || isempty(ersdFile2)
        % Fail loudly rather than silently skipping the comparison: a
        % missing upstream ERSD computation is a pipeline error, not an
        % expected/optional condition.
        if isempty(ersdFile1)
            error("Missing computation of %s", ersdName1)
        else
            error("Missing computation of %s", ersdName2)
        end
    end

    if numel(ersdFile1) == numel(ersdFile2)
        % Equal trial counts on both sides: assume matched/paired design
        % (e.g. same subject, two conditions) and use a paired test.
        compFile = bst_process('CallProcess', 'process_test_permutation2p', ersdFile1, ersdFile2, ...
        'timewindow',     [], ...
        'freqrange',      [], ...
        'rows',           '', ...
        'isabs',          0, ...
        'avgtime',        0, ...
        'avgrow',         0, ...
        'avgfreq',        0, ...
        'matchrows',      1, ...
        'iszerobad',      1, ...
        'Comment',        '', ...
        'test_type',      'ttest_paired', ...  % Paired Student's t-test: T = mean(A-B) / std(A-B) * sqrt(n)
        'randomizations', 1000, ...
        'tail',           'two');  % Two-tailed
    else
        % Unequal trial counts: cannot pair observations, so fall back
        % to an unpaired test with unequal-variance correction.
        compFile = bst_process('CallProcess', 'process_test_permutation2', ersdFile1, ersdFile2, ...
        'timewindow',     [], ...
        'freqrange',      [], ...
        'rows',           '', ...
        'isabs',          0, ...
        'avgtime',        0, ...
        'avgrow',         0, ...
        'avgfreq',        0, ...
        'matchrows',      1, ...
        'iszerobad',      1, ...
        'Comment',        '', ...
        'test_type',      'ttest_unequal', ...  % Student's t-test (unequal variance): t = (mean(A)-mean(B)) / sqrt(var(A)/nA + var(B)/nB)
        'randomizations', 1000, ...
        'tail',           'two');  % Two-tailed
    end

    compFile = bst_process('CallProcess', 'process_set_comment', compFile, [], ...
                'tag',           finalName, ...
                'isindex',       1);
end
end
