function PPA_compute_sources(subName, mainDir, varargin)

    %% Varargin manager
    for i = 1:2:length(varargin)
        switch varargin{i}
            case 'abilitate', abilitate = varargin{i+1};
            case 'atlasName', atlasName = varargin{i+1};
            case 'scoutsName', scoutsName = varargin{i+1};
            case 'cond', cond = varargin{i+1};
        end
    end

    if ~abilitate
        sprintf("Function PPA_compute_sources skipped")
        return
    end
    assert(~isempty(cond), 'PPA_head_model: cond is mandatory')
    assert(~isempty(scoutsName), 'PPA_head_model: scoutsName is mandatory')
    assert(~isempty(atlasName), 'PPA_head_model: atlasName is mandatory')

    %% Find if scout files are already computed
    scoutFiles = bst_process('CallProcess', 'process_select_files_matrix', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           scoutsName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');
    if ~isempty(scoutFiles)
        fprintf("Found scout files, skipping recomputation\n")
        return
    end
    %% Is kernel already computed?
    dataDir = bst_get('ProtocolInfo').STUDIES;
    kernelFile = dir(fullfile(dataDir, subName, cond, '*KERNEL*'));
    

    %% Compute scouts
    if isempty(kernelFile)
        eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     cond, ...
                    'tag',           cond, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
        % Noise covariance check
        cm = dir(fullfile(dataDir, subName, cond, 'noisecov_full.mat'));
        if isempty(cm)
            fprintf("<strong>Noise covariance non trovata, procedo a computarla...</strong>\n")
            iData = [eegFiles.iItem];
            iStudies_data = [eegFiles.iStudy];
            iTargetStudies = unique(iStudies_data);
            bst_noisecov(iTargetStudies, iStudies_data, iData, [], 0);
            cm = dir(fullfile(dataDir, subName, cond, 'noisecov_full.mat'));
        end
        cm = in_bst_data(fullfile(cm.folder,cm.name));
        
        % Process: Compute sources [2018]
        sourceFiles = bst_process('CallProcess', 'process_inverse_2018', eegFiles, [], ...
            'output',  1, ...  % Kernel only: shared
            'inverse', struct(...
                 'Comment',        'dSPM-unscaled: EEG', ...
                 'InverseMethod',  'minnorm', ...
                 'InverseMeasure', 'dspm2018', ...
                 'SourceOrient',   {{'fixed'}}, ...
                 'Loose',          0.2, ...
                 'UseDepth',       1, ...
                 'WeightExp',      0.5, ...
                 'WeightLimit',    10, ...
                 'NoiseMethod',    'reg', ...
                 'NoiseReg',       0.1, ...
                 'SnrMethod',      'fixed', ...
                 'SnrRms',         1e-06, ...
                 'SnrFixed',       3, ...
                 'ComputeKernel',  1, ...
                 'DataTypes',      {{'EEG'}}));
        % Find kernel
        dataDir = bst_get('ProtocolInfo').STUDIES;
        kernelFile = dir(fullfile(dataDir, subName, cond, '*KERNEL*'));        
    end
    kernelFile = fullfile(kernelFile.folder, kernelFile.name);
    % Take atlas from surface
    [subStruct, ~] = bst_get('Subject', subName);
    surfStruct = in_bst_data(subStruct.Surface(strcmp({subStruct.Surface.Comment},'central_15002V')).FileName);
    atlas = surfStruct.Atlas(strcmp({surfStruct.Atlas.Name}, atlasName));
    atlasScoutsName = {atlas.Scouts.Label};
    if ~exist("sourceFiles",'var')
        eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     cond, ...
                    'tag',           cond, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
        eegFiles(~cellfun(@(c) strncmp(c, [cond ' '], length(cond)+1), {eegFiles.Comment})) = [];
        sourceFiles = create_link_files_brainstorm(eegFiles, kernelFile);
    end
    scoutFiles = bst_process('CallProcess', 'process_extract_scout', sourceFiles, [], ...
        'timewindow',     [], ...
        'scouts',         {atlasName, atlasScoutsName}, ...
        'flatten',        1, ...
        'scoutfunc',      'mean', ...  % Mean
        'pcaedit',        struct(...
             'Method',         'pca', ...
             'Baseline',       [-0.1, 0], ...
             'DataTimeWindow', [0, 1], ...
             'RemoveDcOffset', 'file'), ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    0, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', []);

    % Process: Set name: naming_sources
    scoutFiles = bst_process('CallProcess', 'process_set_comment', scoutFiles, [], ...
        'tag',           scoutsName, ...
        'isindex',       1);
end