function PPA_SN_features(subName, mainDir, varargin)
%% Varargin manager

for i = 1:2:length(varargin)
    switch varargin{i}
        case 'abilitate', abilitate = varargin{i+1};
        case 'taskScoutsName', taskScoutsName = varargin{i+1};
        case 'taskContraScoutsName', taskContraScoutsName = varargin{i+1};
        case 'taskCond', taskCond = varargin{i+1};
        case 'restCond', restCond = varargin{i+1};
        case 'restScoutsName', restScoutsName = varargin{i+1};
        case 'tfTaskName', tfTaskName = varargin{i+1};
        case 'tfContraTaskName', tfContraTaskName = varargin{i+1};
        case 'ERSDtaskName', ERSDtaskName = varargin{i+1};
        case 'ERSDcontraTaskName', ERSDcontraTaskName = varargin{i+1};
        case 'phaseTaskName', phaseTaskName = varargin{i+1};
        case 'phaseContraTaskName', phaseContraTaskName = varargin{i+1};
        case 'tfRestName', tfRestName = varargin{i+1};
        case 'ERSDRestName', ERSDRestName = varargin{i+1};
    end

end
if ~abilitate
    sprintf("Funzione PPA_SN_features skipped")
    return
end


% =========================================================================
% ================================ Task ===================================
% =========================================================================
%% Not contralateral

tfFiles = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     taskCond, ...
                    'tag',           tfTaskName, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
if ~ isempty(tfFiles)
    tfFiles(~startsWith({tfFiles.Comment},tfTaskName)) = [];
end
if isempty(tfFiles)
    % Process: Time-frequency (Morlet wavelets)
    scoutFiles = bst_process('CallProcess', 'process_select_files_matrix', [], [], ...
                        'subjectname',   subName, ...
                        'condition',     taskCond, ...
                        'tag',           taskScoutsName, ...
                        'includebad',    0, ...
                        'includeintra',  0, ...
                        'includecommon', 0, ...
                        'outprocesstab', 'no');  % No
    scoutFiles(~startsWith({scoutFiles.Comment},taskScoutsName)) = [];
    tfFiles = bst_process('CallProcess', 'process_timefreq', scoutFiles, [], ...
        'edit',          struct(...
             'Comment',         'Avg,Power,1-30Hz', ...
             'TimeBands',       [], ...
             'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], ...
             'MorletFc',        1, ...
             'MorletFwhmTc',    3, ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'power', ...
             'Output',          'all', ...
             'RemoveEvoked',    0, ...
             'SaveKernel',      0), ...
        'normalize2020', 1, ...
        'normalize',     'none');  % None: Save non-standardized time-frequency maps
    
    % Process: Set name: naming_tf
    tfFiles = bst_process('CallProcess', 'process_set_comment', tfFiles, [], ...
        'tag',           tfTaskName, ...
        'isindex',       1);
end

%% Contralateral
contraTfFiles = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     taskCond, ...
                    'tag',           tfContraTaskName, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
if ~ isempty(contraTfFiles)
    contraTfFiles(~startsWith({contraTfFiles.Comment},tfContraTaskName)) = [];
end
if isempty(contraTfFiles)
    % Process: Time-frequency (Morlet wavelets)
    contraScoutFiles = bst_process('CallProcess', 'process_select_files_matrix', [], [], ...
                        'subjectname',   subName, ...
                        'condition',     taskCond, ...
                        'tag',           taskContraScoutsName, ...
                        'includebad',    0, ...
                        'includeintra',  0, ...
                        'includecommon', 0, ...
                        'outprocesstab', 'no');  % No
    contraTfFiles = bst_process('CallProcess', 'process_timefreq', contraScoutFiles, [], ...
        'edit',          struct(...
             'Comment',         'Avg,Power,1-30Hz', ...
             'TimeBands',       [], ...
             'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], ...
             'MorletFc',        1, ...
             'MorletFwhmTc',    3, ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'power', ...
             'Output',          'all', ...
             'RemoveEvoked',    0, ...
             'SaveKernel',      0), ...
        'normalize2020', 1, ...
        'normalize',     'none');  % None: Save non-standardized time-frequency maps
    
    % Process: Set name: naming_tf
    contraTfFiles = bst_process('CallProcess', 'process_set_comment', contraTfFiles, [], ...
        'tag',           tfContraTaskName, ...
        'isindex',       1);
end

%% ERSD

ersdFiles = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     taskCond, ...
                    'tag',           ERSDtaskName, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
if ~ isempty(ersdFiles)
    ersdFiles(~startsWith({ersdFiles.Comment},ERSDtaskName)) = [];
end
if isempty(ersdFiles)
    % Not contralateral
    ersdFiles = bst_process('CallProcess', 'process_baseline_norm', tfFiles, [], ...
        'baseline',  [-0.300, 0], ...
        'method',    'ersd', ...  % Event-related perturbation (ERS/ERD):    x_std = (x - &mu;) / &mu; * 100
        'overwrite', 0);
    
    % Process: Set name: naming_ersd
    ersdFiles = bst_process('CallProcess', 'process_set_comment', ersdFiles, [], ...
        'tag',           ERSDtaskName, ...
        'isindex',       1);
end

% Contralaterale
ersdContrFiles = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     taskCond, ...
                    'tag',           ERSDcontraTaskName, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
if ~isempty(ersdContrFiles)
    ersdContrFiles(~startsWith({ersdContrFiles.Comment},ERSDcontraTaskName)) = [];
end
if isempty(ersdContrFiles)
    
    % Process: Event-related perturbation (ERS/ERD): [-301ms,-4ms]
    ersdContrFiles = bst_process('CallProcess', 'process_baseline_norm', contraTfFiles, [], ...
        'baseline',  [-0.300, 0], ...
        'method',    'ersd', ...  % Event-related perturbation (ERS/ERD):    x_std = (x - &mu;) / &mu; * 100
        'overwrite', 0);
    
    % Process: Set name: naming_ersd
    ersdContrFiles = bst_process('CallProcess', 'process_set_comment', ersdContrFiles, [], ...
        'tag',           ERSDcontraTaskName, ...
        'isindex',       1);
end

%% ITPC phase - related

% Not contralateral

phaseFiles = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     taskCond, ...
                    'tag',           phaseTaskName, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
if ~isempty(phaseFiles)
    phaseFiles(~startsWith({phaseFiles.Comment},phaseTaskName)) = [];
end
if isempty(phaseFiles)
    scoutFiles = bst_process('CallProcess', 'process_select_files_matrix', [], [], ...
                        'subjectname',   subName, ...
                        'condition',     taskCond, ...
                        'tag',           taskScoutsName, ...
                        'includebad',    0, ...
                        'includeintra',  0, ...
                        'includecommon', 0, ...
                        'outprocesstab', 'no');  % No
    scoutFiles(~startsWith({scoutFiles.Comment},taskScoutsName)) = [];
    % Process: Time-frequency (Morlet wavelets)
    phaseFiles = bst_process('CallProcess', 'process_timefreq', scoutFiles, [], ...
        'edit',          struct(...
             'Comment',         'Complex,1-30Hz', ...
             'TimeBands',       [], ...
             'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], ...
             'MorletFc',        1, ...
             'MorletFwhmTc',    3, ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'none', ...
             'Output',          'all', ...
             'RemoveEvoked',    0, ...
             'SaveKernel',      0), ...
        'normalize2020', 1, ...
        'normalize',     'none');  % None: Save non-standardized time-frequency maps
    
    % Process: Set name: naming_tf_for_phases
    phaseFiles = bst_process('CallProcess', 'process_set_comment', phaseFiles, [], ...
        'tag',           phaseTaskName, ...
        'isindex',       1);
end

% =========================================================================
% ================================ Rest ===================================
% =========================================================================

%% Time-frequency

tfFiles = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     restCond, ...
                    'tag',           tfRestName, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
if ~isempty(tfFiles)
    tfFiles(~startsWith({tfFiles.Comment},tfRestName)) = [];
end
if isempty(tfFiles)
    % Process: Time-frequency (Morlet wavelets)
    scoutFiles = bst_process('CallProcess', 'process_select_files_matrix', [], [], ...
                        'subjectname',   subName, ...
                        'condition',     restCond, ...
                        'tag',           restScoutsName, ...
                        'includebad',    0, ...
                        'includeintra',  0, ...
                        'includecommon', 0, ...
                        'outprocesstab', 'no');  % No
    tfFiles = bst_process('CallProcess', 'process_timefreq', scoutFiles, [], ...
        'edit',          struct(...
             'Comment',         'Avg,Power,1-30Hz', ...
             'TimeBands',       [], ...
             'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], ...
             'MorletFc',        1, ...
             'MorletFwhmTc',    3, ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'power', ...
             'Output',          'all', ...
             'RemoveEvoked',    0, ...
             'SaveKernel',      0), ...
        'normalize2020', 1, ...
        'normalize',     'none');  % None: Save non-standardized time-frequency maps
    
    % Process: Set name: naming_tf
    tfFiles = bst_process('CallProcess', 'process_set_comment', tfFiles, [], ...
        'tag',           tfRestName, ...
        'isindex',       1);
end

%% ERSD

ersdFiles = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                    'subjectname',   subName, ...
                    'condition',     restCond, ...
                    'tag',           ERSDRestName, ...
                    'includebad',    0, ...
                    'includeintra',  0, ...
                    'includecommon', 0, ...
                    'outprocesstab', 'no');  % No
if ~isempty(ersdFiles)
    ersdFiles(~startsWith({ersdFiles.Comment},ERSDRestName)) = [];
end
if isempty(ersdFiles)
    % Not contralaterale
    % Process: Event-related perturbation (ERS/ERD): [-301ms,-4ms]
    ersdFiles = bst_process('CallProcess', 'process_baseline_norm', tfFiles, [], ...
        'baseline',  [-0.300, 0], ...
        'method',    'ersd', ...  % Event-related perturbation (ERS/ERD):    x_std = (x - &mu;) / &mu; * 100
        'overwrite', 0);
    
    % Process: Set name: naming_ersd
    ersdFiles = bst_process('CallProcess', 'process_set_comment', ersdFiles, [], ...
        'tag',           ERSDRestName, ...
        'isindex',       1);
end

end