function PPA_compute_PSD_channels(subName, mainDir, varargin)
%% Varargin manager

% Default values
cond = [];
psdName = [];
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'abilitate', abilitate = varargin{i+1};
        case 'PSDname', psdName = varargin{i+1};
        case 'cond', cond = varargin{i+1};
        case 'computeAverage', computeAverage = varargin{i+1};
        case 'avgName', avgName = varargin{i+1};
    end
end

if ~abilitate
    sprintf("Funzione PPA_SN_features skipped")
    return
end
% Mandatory
assert(~isempty(cond), 'cond is mandatory for extract_band_relative_powers');
assert(~isempty(psdName), 'PSDname is mandatory for extract_band_relative_powers');
assert(~isempty(cond), 'cond is mandatory for extract_band_relative_powers');
assert(~isempty(psdName), 'PSDname is mandatory for extract_band_relative_powers');

%% Find PSD file, if already compute
psdFile = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           psdName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
% If empty, compute
if isempty(psdFile)
    fprintf("PSD file not found for subject %s, starting computation\n", subName);
    eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           cond, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
    eegFiles(~cellfun(@(c) strncmp(c, [cond ' '], length(cond)+1), {eegFiles.Comment})) = [];
    psdFile = bst_process('CallProcess', 'process_psd', eegFiles, [], ...
    'timewindow',  [], ...
    'win_length',  1, ...
    'win_overlap', 50, ...
    'units',       'physical', ...  % Physical: U2/Hz
    'sensortypes', 'EEG', ...
    'win_std',     0, ...
    'edit',        struct(...
         'Comment',         psdName, ...
         'TimeBands',       [], ...
         'Freqs',           [], ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'all', ...
         'SaveKernel',      0));
    psdFile = bst_process('CallProcess', 'process_tf_norm', psdFile, [], ...
        'normalize', 'relative2020', ...  % Relative power (divide by total power)
        'overwrite', 1);
    psdFile = bst_process('CallProcess', 'process_set_comment', psdFile, [], ...
            'tag',           psdName, ...
            'isindex',       1);
end

%% Average
if computeAverage
    % Find file
    avgPSDFile = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           avgName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
    % If empty, compute
    if isempty(avgPSDFile)
        eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           cond, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
        eegFiles(~cellfun(@(c) strncmp(c, [cond ' '], length(cond)+1), {eegFiles.Comment})) = [];
        avgPSDFile = bst_process('CallProcess', 'process_psd', eegFiles, [], ...
        'timewindow',  [], ...
        'win_length',  1, ...
        'win_overlap', 50, ...
        'units',       'physical', ...  % Physical: U2/Hz
        'sensortypes', 'EEG', ...
        'win_std',     0, ...
        'edit',        struct(...
             'Comment',         avgName, ...
             'TimeBands',       [], ...
             'Freqs',           [], ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'power', ...
             'Output',          'average', ...
             'SaveKernel',      0));
        avgPSDFile = bst_process('CallProcess', 'process_tf_norm', avgPSDFile, [], ...
        'normalize', 'relative2020', ...  % Relative power (divide by total power)
        'overwrite', 1);
        avgPSDFile = bst_process('CallProcess', 'process_set_comment', avgPSDFile, [], ...
                'tag',           avgName, ...
                'isindex',       1);
    end
end
end