function PPA_SN_ROI_features(subName, mainDir, varargin)
% PPA_SN_ROI_features - Extract relevant features for best ROI selection: 
% ITPC (Low Beta, Theta), sync/desync power, ttest vs Rest, ttest vs Controlaterale.

%% Varargin manager
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'abilitate',           abilitate             = varargin{i+1};
        case 'itpcSearch',          itpcSearch            = varargin{i+1};
        case 'ersdSearchWordTask',  ersdSearchWordTask    = varargin{i+1};
        case 'ersdSearchWordContra',ersdSearchWordContra  = varargin{i+1};
        case 'ersdSearchWordRest',  ersdSearchWordRest    = varargin{i+1};
        case 'taskCond',            taskCond              = varargin{i+1};
        case 'restCond',            restCond              = varargin{i+1};
        case 'lowBetaLim',          lowBetaLim            = varargin{i+1};
        case 'thetaLim',            thetaLim              = varargin{i+1};
        case 'minITPCvalue',        minITPCvalue          = varargin{i+1};
        case 'timeLimit',           timeLimit             = varargin{i+1};
        case 'syncValues',          syncValues            = varargin{i+1};
        case 'timeLimitTtest',      timeLimitTtest        = varargin{i+1};
        case 'tThreshold',          tThreshold            = varargin{i+1};
        case 'renameTtestRest',     renameTtestRest       = varargin{i+1};
        case 'renameTtestContra',   renameTtestContra     = varargin{i+1};
        case 'resultsDir',          resultsDir            = varargin{i+1};
        case 'resultsFile',         resultsFile           = varargin{i+1};
        case 'bandNames',           bandNames             = varargin{i+1};
    end
end

if ~abilitate
    sprintf("Funzione PPA_SN_ROI_features skipped")
    return
end

%% Brainstorm setup
protocolStruct = bst_get('ProtocolInfo');
data = protocolStruct.STUDIES;

%% ITPC
itpcFiles = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
    'subjectname',   subName, ...
    'condition',     taskCond, ...
    'tag',           itpcSearch, ...
    'includebad',    0, ...
    'includeintra',  0, ...
    'includecommon', 0, ...
    'outprocesstab', 'no');
itpcFiles(contains({itpcFiles.Comment}, 'contralateral')) = [];

itpcStruct = calcolate_ITPC_2(itpcFiles);
itpcStruct = extract_significant_itpc(itpcStruct, lowBetaLim, 'Low_beta', minITPCvalue);
itpcStruct = extract_significant_itpc(itpcStruct, thetaLim,   'Theta',    minITPCvalue);

%% Sync / desync power
powStruct = extract_relevant_sync_desync( ...
    'sub',          subName, ...
    'cond',         taskCond, ...
    'searchWord',   ersdSearchWordTask, ...
    'excludeContra',true, ...
    'timeLimit',    timeLimit, ...
    'freqLimit',    [thetaLim, lowBetaLim], ...
    'bandName',     bandNames, ...
    'direction',    {'ascend', 'descend'}, ...
    'syncvalues',   syncValues ...
);

%% Ttest Task vs Rest
ttestRest = extract_ttest_features(subName, ersdSearchWordTask, data, ...
    'freqlimits',       [thetaLim, lowBetaLim], ...
    'type',             {'Sync', 'Desync'}, ...
    'bandname',         bandNames, ...
    'cond1',            taskCond, ...
    'cond2',            restCond, ...
    'isContra1',        false, ...
    'isContra2',        false, ...
    'searchWord1',      ersdSearchWordTask, ...
    'searchWord2',      ersdSearchWordRest, ...
    'timelimitsttest',  timeLimitTtest, ...
    'rename_ttest',     renameTtestRest, ...
    'tthreshold',       tThreshold ...
);

%% Ttest Task vs Controlaterale
ttestContra = extract_ttest_features(subName, ersdSearchWordTask, data, ...
    'freqlimits',       [thetaLim, lowBetaLim], ...
    'type',             {'Sync', 'Desync'}, ...
    'bandname',         {'Theta', 'Low_beta'}, ...
    'cond1',            taskCond, ...
    'cond2',            taskCond, ...
    'isContra1',        false, ...
    'isContra2',        true, ...
    'searchWord1',      ersdSearchWordTask, ...
    'searchWord2',      ersdSearchWordContra, ...
    'timelimitsttest',  timeLimitTtest, ...
    'rename_ttest',     renameTtestContra, ...
    'tthreshold',       tThreshold ...
);

% Fallback with empty contralateral
if isempty(ttestContra)
    ttestContra = ttestRest;
    ttestContra.Theta.isActive   = false(length(ttestContra.Theta.isActive),   1);
    ttestContra.Theta.MeanValue  = zeros(length(ttestContra.Theta.MeanValue),  1);
    ttestContra.Low_beta.isActive  = false(length(ttestContra.Low_beta.isActive),  1);
    ttestContra.Low_beta.MeanValue = zeros(length(ttestContra.Low_beta.MeanValue), 1);
end

%% Results assemble
results.(subName).ITPC        = itpcStruct;
results.(subName).Power       = powStruct;
results.(subName).Restttest   = ttestRest;
results.(subName).Contrattest = ttestContra;

%% Merge with previous results and store
resultsPath = fullfile(resultsDir, resultsFile);
if isfile(resultsPath)
    prevResults = load(resultsPath).results;
    prevResults.(subName) = results.(subName);
    results = prevResults;
end
save(resultsPath, 'results');

end