function PPA_compute_mean_ERSD(subName, mainDir, varargin)
%% Varargin manager

% Default values
cond = [];
psdName = [];
computeAverage = false;
avgName = '';
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'abilitate', abilitate = varargin{i+1};
        case 'ersdName', ersdName = varargin{i+1};
        case 'cond', cond = varargin{i+1};
        case 'avgName', avgName = varargin{i+1};
    end
end

if ~abilitate
    sprintf("Funzione PPA_compute_mean_ERSD_channels skipped")
    return
end
% Mandatory
assert(~isempty(cond), 'cond parameter is mandatory for extract_band_relative_powers');
assert(~isempty(ersdName), 'ersdName parameter is mandatory for extract_band_relative_powers');
assert(~isempty(avgName), 'avgName parameter is mandatory for extract_band_relative_powers');

%% Computa la media
% Search already computed file
meanFile = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           avgName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
if isempty(meanFile)
    % Find ERSD files
    ersdFiles = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           ersdName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
    ersdFiles(~cellfun(@(c) strncmp(c, [ersdName ' '], length(ersdName)+1), {ersdFiles.Comment})) = [];
    meanFile = bst_process('CallProcess', 'process_average', ersdFiles, [], ...
                'avgtype',       1, ...  % Everything
                'avg_func',      1, ...  % Arithmetic average:  mean(x)
                'weighted',      0, ...
                'matchrows',     1, ...
                'iszerobad',     1);
    meanFile = bst_process('CallProcess', 'process_set_comment', meanFile, [], ...
                'tag',           avgName, ...
                'isindex',       1);
end

end