function PPA_compute_normalized_PSD_channels(subName, mainDir, varargin)
    %% Varargin manager
    
    % Default values
    cond = [];
    psdName = [];
    for i = 1:2:length(varargin)
        switch varargin{i}
            case 'abilitate', abilitate = varargin{i+1};
            case 'cond', cond = varargin{i+1};
            case 'avgName', avgName = varargin{i+1};
        end
    end
    
    if ~abilitate
        sprintf("Funzione PPA_SN_features skipped")
        return
    end
    % Mandatory
    assert(~isempty(cond), 'cond parameter is mandatory for extract_band_relative_powers');
    assert(~isempty(avgName), 'avgName parameter is mandatory extract_band_relative_powers');


%% Average
% Find file
avgPSDFile = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
            'subjectname',   subName, ...
            'condition',     cond, ...
            'tag',           avgName, ...
            'includebad',    0, ...
            'includeintra',  0, ...
            'includecommon', 0, ...
            'outprocesstab', 'no');  % No
    if isempty(avgPSDFile)
        eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           cond, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
        eegFiles(~cellfun(@(c) strncmp(c, [cond ' '], length(cond)+1), {eegFiles.Comment})) = [];
    
        % Process: Power spectrum density (Welch)
        sFiles = bst_process('CallProcess', 'process_psd', eegFiles, [], ...
            'timewindow',  [], ...
            'win_length',  1, ...
            'win_overlap', 50, ...
            'units',       'physical', ...  % Physical: U2/Hz
            'win_std',     0, ...
            'edit',        struct(...
                 'Comment',         'Avg,Power', ...
                 'TimeBands',       [], ...
                 'Freqs',           [], ...
                 'ClusterFuncTime', 'none', ...
                 'Measure',         'power', ...
                 'Output',          'average', ...
                 'SaveKernel',      0));
        
        % Process: Spectrum normalization
        sFiles = bst_process('CallProcess', 'process_tf_norm', sFiles, [], ...
            'normalize', 'relative2020', ...  % Relative power (divide by total power)
            'overwrite', 1);
        
        % Process: Group in time or frequency bands
        sFiles = bst_process('CallProcess', 'process_tf_bands', sFiles, [], ...
            'isfreqbands', 1, ...
            'freqbands',   {'delta', '1, 4', 'mean'; 'theta', '5, 7', 'mean'; 'alpha', '8, 12', 'mean'; 'beta', '15, 29', 'mean'; 'gamma1', '30, 59', 'mean'}, ...
            'istimebands', 0, ...
            'timebands',   '', ...
            'overwrite',   1);
        
        % Process: Set name: Grouped_normalized_PSD_SOC_scouts
        sFiles = bst_process('CallProcess', 'process_set_comment', sFiles, [], ...
            'tag',           avgName, ...
            'isindex',       1);
    end
end