function PPA_extract_freq_bands(subName, mainDir, varargin)
% Default values
cond = [];
bands = [];
PSDname = [];
bandsName = [];
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'abilitate', abilitate = varargin{i+1};
        case 'PSDname', PSDname = varargin{i+1};
        case 'cond', cond = varargin{i+1};
        case 'bands', bands = varargin{i+1};
        case 'bandsName', bandsName = varargin{i+1};
    end
end

if ~abilitate
    sprintf("Function PPA_extract_PSD_bands skipped")
    return
end
% Mandatory
assert(~isempty(PSDname), 'PSDname is mandatory for extract_band_relative_powers');
assert(~isempty(cond), 'cond is mandatory for extract_band_relative_powers');
assert(~isempty(bands), 'bands is mandatory for extract_band_relative_powers');
assert(~isempty(bandsName), 'bandsName is mandatory for extract_band_relative_powers');

%% Compute grouped frequencies if missing
bandsFile = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           bandsName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
if ~isempty(bandsFile)
    bandsFile(~cellfun(@(c) strncmp(c, [bandsName ' '], length(bandsName)+1), {bandsFile.Comment})) = [];
end
if isempty(bandsFile)
    % Find PSDs
    psds = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           PSDname, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
    psds(~cellfun(@(c) strncmp(c, [PSDname ' '], length(PSDname)+1), {psds.Comment})) = [];
    fn = fieldnames(bands);
    freqbands = cell(numel(fn), 3);
    for i = 1:numel(fn)
        freqbands{i,1} = fn{i};
        freqbands{i,2} = sprintf('%g, %g', bands.(fn{i})(1), bands.(fn{i})(2));
        freqbands{i,3} = 'mean';
    end
    bandsFile = bst_process('CallProcess', 'process_tf_bands', psds, [], ...
                'isfreqbands', 1, ...
                'freqbands',   freqbands, ...
                'istimebands', 0, ...
                'timebands',   '', ...
                'overwrite',   0);
    bandsFile = bst_process('CallProcess', 'process_set_comment', bandsFile, [], ...
                'tag',           bandsName, ...
                'isindex',       1);
end
end