function psd_struct = PPA_extract_band_relative_powers(subName, mainDir, varargin)
%% Varargin manager

% Default values
bands = struct('Alpha', [8,13],'Beta', [14,30],'Theta', [1,7],'Gamma', [30,45]);
cond = [];
psdName = [];
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'Bands', bands = varargin{i+1};
        case 'PSDname', psdName = varargin{i+1};
        case 'cond', cond = varargin{i+1};
    end
end

% Mandatory
assert(~isempty(cond), 'cond is mandatory for extract_band_relative_powers');
assert(~isempty(psdName), 'PSDname is mandatory for extract_band_relative_powers');
%% Find PSD file if already computed
psdFile = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           psdName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
% If empty, compute
if isempty(psdFile)
    fprintf("PSD file non trovato per il soggetto %s, procedo a computarlo\n", subName);
    eegFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           cond, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
    eegFiles(~startsWith({eegFiles.Comment}, cond)) = []; % Remove unwanted files
    psdFile = bst_process('CallProcess', 'process_psd', eegFiles, [], ...
    'timewindow',  [], ...
    'win_length',  1, ...
    'win_overlap', 50, ...
    'units',       'physical', ...  % Physical: U2/Hz
    'sensortypes', 'EEG', ...
    'win_std',     0, ...
    'edit',        struct(...
         'Comment',         psdName, ...
         'TimeBands',       [], ...
         'Freqs',           [], ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'average', ...
         'SaveKernel',      0));
    psdFile = bst_process('CallProcess', 'process_set_comment', psdFile, [], ...
            'tag',           psdName, ...
            'isindex',       1);
end

%% Compute relative PSD
PSD = in_bst_timefreq(psdFile.FileName);
chans = PSD.RowNames;
numChans = numel(chans);
data = squeeze(PSD.TF);
frequencies = PSD.Freqs;

psd_struct = struct();
bandNames = fieldnames(bands);
numBands = numel(bandNames);

% Check band intervals
allBandMask = false(size(frequencies));
for b = 1:numBands
    lims = bands.(bandNames{b});
    allBandMask = allBandMask | (frequencies >= lims(1) & frequencies <= lims(2));
end

for b = 1:numBands
    currBand = bandNames{b};
    psd_struct.(currBand) = struct();
    lims = bands.(currBand);
    for c = 1:numChans
        chanName = chans{c};
        chanPower = sum(data(c, allBandMask)); 
        bandPower = sum(data(c, frequencies >= lims(1) & frequencies <= lims(2)));
        psd_struct.(currBand).(chanName) = bandPower / chanPower * 100;
    end
end
end