function PPA_compute_ERSD_scouts(subName, mainDir, varargin)
% PPA_COMPUTE_ERSD_SCOUTS  Computes (or retrieves, if cached) the
%   scout-level (source-space) ERSD for a subject/condition, using the
%   same Morlet + baseline z-score pipeline as PPA_compute_ERSD_channels
%   but starting from scout time series instead of sensor-level data.
%
%   Parameters (varargin, name-value pairs):
%     cond        - (required) Brainstorm condition folder to process
%     ersdName    - (required) tag identifying/labeling the output ERSD
%                   file (used to detect already-computed results)
%     atlasName   - (required) cortical atlas used to define the scouts
%     scoutsName  - (required) tag used to find the source scout files
%                   the ERSD should be computed from
%     abilitate   - bool, if false the function is skipped entirely

% Default values
cond = [];
ersdName = [];
for i = 1:2:length(varargin)
    switch varargin{i}
        case 'ersdName', ersdName = varargin{i+1};
        case 'cond', cond = varargin{i+1};
        case 'atlasName', atlasName = varargin{i+1};
        case 'scoutsName', scoutsName = varargin{i+1};
        case 'abilitate', abilitate = varargin{i+1};
    end
end

if ~abilitate
    sprintf("Function PPA_compute_ERSD_scouts skipped")
    return
end
% Required parameters
assert(~isempty(cond), 'Parameter cond is required by extract_band_relative_powers');
assert(~isempty(ersdName), 'Parameter ersdName is required by extract_band_relative_powers');
assert(~isempty(atlasName), 'Parameter atlasName is required by extract_band_relative_powers');
assert(~isempty(scoutsName), 'Parameter scoutsName is required by extract_band_relative_powers');

%% Look for an existing ERSD file
ersdFile = bst_process('CallProcess', 'process_select_files_timefreq', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           ersdName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
if ~isempty(ersdFile)
    % Tag-based search can return partial/prefix matches; keep only
    % files whose comment starts exactly with "<ersdName> " to avoid
    % picking up unrelated files that merely share a substring.
    ersdFile(~cellfun(@(c) strncmp(c, [ersdName ' '], length(ersdName)+1), {ersdFile.Comment})) = [];
end
if isempty(ersdFile)
    fprintf("PSD file not found for subject %s, computing it now\n", subName);
    eegFiles = bst_process('CallProcess', 'process_select_files_matrix', [], [], ...
                'subjectname',   subName, ...
                'condition',     cond, ...
                'tag',           scoutsName, ...
                'includebad',    0, ...
                'includeintra',  0, ...
                'includecommon', 0, ...
                'outprocesstab', 'no');  % No
    eegFiles(~startsWith({eegFiles.Comment}, scoutsName)) = []; % Discard any spurious/unrelated files
    % Process: Time-frequency (Morlet wavelets)
    % Same 1-60 Hz decomposition settings as the channel-level pipeline,
    % applied here to scout (source-space) time series.
    ersdFile = bst_process('CallProcess', 'process_timefreq', eegFiles, [], ...
        'edit',          struct(...
             'Comment',         'Power,1-60Hz', ...
             'TimeBands',       [], ...
             'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], ...
             'MorletFc',        1, ...
             'MorletFwhmTc',    3, ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'power', ...
             'Output',          'all', ...
             'RemoveEvoked',    0, ...
             'SaveKernel',      0), ...
        'normalize2020', 1, ...
        'normalize',     'none');  % None: save non-standardized time-frequency maps

    % Process: Z-score transformation over the [-301ms, -4ms] baseline
    % window (pre-stimulus baseline normalization).
    ersdFile = bst_process('CallProcess', 'process_baseline_norm', ersdFile, [], ...
        'baseline',  [-0.30078125, -0.00390625], ...
        'method',    'zscore', ...  % Z-score transformation: x_std = (x - mu) / sigma
        'overwrite', 1);
    ersdFile = bst_process('CallProcess', 'process_set_comment', ersdFile, [], ...
            'tag',           ersdName, ...
            'isindex',       1);
end
end
